### ISSUE TITLE
CTD on equip bow and arrows

### ISSUE THREAD

**Issue by mikeroygray** [Ryan-rsm-McKenzie/DynamicEquipmentManagerSSE#5]
I put a note in the comments section, but this may be the better place to report a bug. Clearly, not everyone gets this, and I have a very heavy load order - but I've restarted the game (using LaL) several times, and I DO always  get the CTD.
https://pastebin.com/TTS2ByAh

**Comment by mikeroygray** [comment]
Wow. That was a revelation. I get it no matter what I do. I reduced all the way to absolute zero. Removed ENB. Put the vanilla DLC .esm files back to original state (i.e., no error correction). Note: SkyUI. All I have now is Vanilla SE + SKSE + DEM. (Also removed bink_ stuff from .Net Framework.) 
Test: Start from MO2, coc riverwood, open inventory, activate the bow = ctd. (Note: I don't seem to get the CTD until I move the mouse in the inventory list.)

**Comment by SniffleMan** [comment]
Do you have other skse plugins?

**Comment by mikeroygray** [comment]
NONE.

**Comment by mikeroygray** [comment]
I mean, usually, yes! But not now.

**Comment by mikeroygray** [comment]
More:
1) Heck, I even just rebooted, and I can still reproduce the CTD. (That one had me a little scared. I REALLY didn't want to start again from scratch!)
2) I just reactivated .NET Framework to get a crash log. That's ALL I have activated, nothing else besides SE, SKSE v.12, DEM, .NET Framework.

https://pastebin.com/RUs6xRTD

(Check the tail end for confirmation about empty loadorder!)

What do you think - shall I ask Meh321 if he has any insight? Maybe some kind of weird SKSE bug? Sometimes he can figure out esoteric stuff like that. (The menu crash reminds me of a problem I was having with Better Spell Learning, that turned out to hinge on a problem with SKSE.)

**Comment by mikeroygray** [comment]
P.S. This last crash (pastebin link) did not come instantly. First time I activated the bow, no crash. Then I switched to war-axe, then back to bow a couple times. CTD on about third bow activation.

**Comment by SniffleMan** [comment]
Try sending me a save where this causes a crash

**Comment by mikeroygray** [comment]
Not ignoring you here - I'm away a lot just now. I'll put a save on my google drive and link as soon as I can.

**Comment by Ryan-rsm-McKenzie** [comment]
Fixed in 1.4.0

**Comment by mikeroygray** [comment]
Damn - sorry for flaking out on this. I ran out of time, then I kind of forgot ...  And: THANKS for for the fix!!
